language: ruby
bundler_args: --without development
rvm: 1.9.3

notifications:
  recipients:
    - apark73@gmail.com

before_script:
  # - "psql -c 'create database sprinter_test;' -U postgres"
  - "bundle exec rake db:drop db:create db:migrate db:test:prepare"