development:
 adapter: postgresql
 encoding: unicode
 host: localhost
 database: sprinter_development
 pool: 5
 username: postgres
 password: postgres

test:
 adapter: postgresql
 encoding: unicode
 host: localhost
 database: sprinter_test
 pool: 5
 username: postgres
 password: postgres

production:
 adapter: postgresql
 encoding: unicode
 database: sprinter_production
 pool: 5
 username: postgres
 password: 